name: Test Api
on:
  push:
    paths:
      - api/**
jobs:
  build:
    name: Test with Pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env file
        run: |
          cp .env.example .env
      - name: Test with pytest
        run: |
          pytest --cov=.
